source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TKParallaxScrollView_Example', :exclusive => true do
  pod 'TKParallaxScrollView', :path => '../'
end

target 'TKParallaxScrollView_Tests', :exclusive => true do
  pod 'TKParallaxScrollView', :path => '../'

  
end
